[build]
  command = "npm run build"
  publish = "_site"

[[plugins]]
package = "netlify-plugin-checklinks"

  [plugins.inputs]
  # Checklinks outputs TAP (https://testanything.org/tap-version-13-specification.html)
  # by default. Enabling pretty mode makes the output easier on the eyes.
  pretty = true