on:
  repository_dispatch:
    types: [update_ds]

jobs:
  Update-DS-Agency-Package:
    name: Update DS-Agency Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.16"
      - name: Update DS-Agency Package
        run: npm update @kickstartds/ds-agency
      - name: Check for changes
        id: check_changes
        continue-on-error: true
        run: test -n "$(git status --porcelain)"
      - name: Push changes
        if: steps.check_changes.outcome == 'success'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add package.json package-lock.json
          git commit -m "chore: update ds-agency"
          git push
