on:
  repository_dispatch:
    types: [update_ds]

jobs:
  Update-DS-Agency-Package:
    name: Update DS-Agency Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.16"
      - name: Update DS-Agency Package
        run: npm update @kickstartds/ds-agency
      - name: Check for changes
        run:  echo "HAS_CHANGES=$(git diff-index --quiet HEAD || echo $?)" >> $GITHUB_ENV
      - name: Push changes
        if: env.HAS_CHANGES == 1
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add package.json package-lock.json
          git commit -m "chore: update ds-agency"
          git push
